// Code generated by protoc-gen-go.
// source: helloworld.proto
// DO NOT EDIT!

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld.proto

It has these top-level messages:
	RegisterRequest
	StatusReply
	HelloRequest
	CalenderDay
	HelloReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusReply struct {
	Status uint32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *StatusReply) Reset()                    { *m = StatusReply{} }
func (m *StatusReply) String() string            { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()               {}
func (*StatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The request message containing the user's name.
type HelloRequest struct {
	Name  string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Birth *CalenderDay `protobuf:"bytes,2,opt,name=birth" json:"birth,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloRequest) GetBirth() *CalenderDay {
	if m != nil {
		return m.Birth
	}
	return nil
}

type CalenderDay struct {
	Day   int32 `protobuf:"varint,1,opt,name=day" json:"day,omitempty"`
	Month int32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	Year  int32 `protobuf:"varint,3,opt,name=year" json:"year,omitempty"`
}

func (m *CalenderDay) Reset()                    { *m = CalenderDay{} }
func (m *CalenderDay) String() string            { return proto.CompactTextString(m) }
func (*CalenderDay) ProtoMessage()               {}
func (*CalenderDay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "helloworld.RegisterRequest")
	proto.RegisterType((*StatusReply)(nil), "helloworld.StatusReply")
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*CalenderDay)(nil), "helloworld.CalenderDay")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Greeter service

type GreeterClient interface {
	// Registers a new client certificate
	// rpc Register (RegisterRequest) returns (StatusReply) {}
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Registers a new client certificate
	// rpc Register (RegisterRequest) returns (StatusReply) {}
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for Pairing service

type PairingClient interface {
	// Registers a new client certificate
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type pairingClient struct {
	cc *grpc.ClientConn
}

func NewPairingClient(cc *grpc.ClientConn) PairingClient {
	return &pairingClient{cc}
}

func (c *pairingClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/helloworld.Pairing/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pairing service

type PairingServer interface {
	// Registers a new client certificate
	Register(context.Context, *RegisterRequest) (*StatusReply, error)
}

func RegisterPairingServer(s *grpc.Server, srv PairingServer) {
	s.RegisterService(&_Pairing_serviceDesc, srv)
}

func _Pairing_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Pairing/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pairing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Pairing",
	HandlerType: (*PairingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Pairing_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x51, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0xdd, 0x9c, 0xdd, 0xe6, 0x37, 0x65, 0x23, 0xc8, 0x2c, 0xdb, 0x45, 0x02, 0x8a, 0x17, 0x8b,
	0xcc, 0xbb, 0x87, 0x29, 0xe8, 0x0e, 0x42, 0xcd, 0x0e, 0x9e, 0x33, 0xfb, 0xd1, 0x15, 0xd2, 0xa6,
	0x26, 0x19, 0xda, 0x7f, 0x6f, 0x93, 0xb5, 0x18, 0x45, 0xbc, 0x7d, 0xef, 0xe5, 0xe5, 0x7d, 0x2f,
	0x2f, 0x30, 0xd9, 0xa2, 0x10, 0xf2, 0x43, 0x2a, 0x91, 0x44, 0xa5, 0x92, 0x46, 0x12, 0xf8, 0x66,
	0xe8, 0x05, 0x8c, 0x19, 0xa6, 0x99, 0x36, 0xa8, 0x18, 0xbe, 0xef, 0x50, 0x1b, 0x42, 0xe0, 0xb0,
	0xe0, 0x39, 0x86, 0xdd, 0xf3, 0xee, 0xd5, 0x11, 0x73, 0x73, 0x2d, 0x1b, 0xad, 0x0d, 0x37, 0x3b,
	0xcd, 0xb0, 0x14, 0x15, 0x99, 0x42, 0x5f, 0x3b, 0xe8, 0x44, 0x27, 0xac, 0x41, 0xf4, 0x05, 0x8e,
	0x9f, 0xac, 0xf7, 0x3f, 0x56, 0xe4, 0x1a, 0x82, 0x4d, 0xa6, 0xcc, 0x36, 0x3c, 0xa8, 0xc9, 0xd1,
	0xe2, 0x2c, 0xf2, 0xf2, 0xdd, 0x73, 0x81, 0x45, 0x82, 0xea, 0x81, 0x57, 0x6c, 0xaf, 0xa2, 0x2b,
	0x18, 0x79, 0x2c, 0x99, 0x40, 0x2f, 0xe1, 0x95, 0x33, 0x0c, 0x98, 0x1d, 0xc9, 0x29, 0x04, 0xb9,
	0x2c, 0x1a, 0xbf, 0x80, 0xed, 0x81, 0xdd, 0x5c, 0x21, 0x57, 0x61, 0xcf, 0x91, 0x6e, 0xa6, 0x97,
	0x00, 0x4d, 0x3a, 0xfb, 0x86, 0x10, 0x06, 0x39, 0x6a, 0xcd, 0xd3, 0x36, 0x5e, 0x0b, 0x17, 0x2b,
	0x18, 0x3c, 0x2a, 0xc4, 0xba, 0x12, 0x72, 0x07, 0xc3, 0x35, 0xaf, 0xdc, 0x2d, 0x12, 0xfa, 0x49,
	0xfd, 0x67, 0xce, 0xa6, 0x7f, 0x9c, 0xd4, 0x2b, 0x68, 0x67, 0xf1, 0x0c, 0x83, 0x98, 0x67, 0x2a,
	0x2b, 0x52, 0xb2, 0x84, 0x61, 0xdb, 0x34, 0x99, 0xfb, 0x17, 0x7e, 0xf5, 0x3f, 0xfb, 0xd1, 0x88,
	0xd7, 0x3a, 0xed, 0x2c, 0x6f, 0x60, 0x9e, 0xc9, 0x28, 0x55, 0xe5, 0x5b, 0x84, 0x9f, 0x3c, 0x2f,
	0x05, 0x6a, 0x4f, 0xbc, 0x1c, 0xbb, 0xdd, 0xaf, 0x76, 0x8e, 0xed, 0x4f, 0xc7, 0xdd, 0x4d, 0xdf,
	0x7d, 0xf9, 0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x57, 0x2e, 0x95, 0x06, 0x02, 0x00,
	0x00,
}
