// Code generated by protoc-gen-go.
// source: pairing.proto
// DO NOT EDIT!

/*
Package pairing is a generated protocol buffer package.

It is generated from these files:
	pairing.proto

It has these top-level messages:
	RegisterRequest
	StatusReply
*/
package pairing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_REGISTERED       Status = 0
	Status_WAITING_APPROVAL Status = 1
	Status_REJECTED         Status = 2
)

var Status_name = map[int32]string{
	0: "REGISTERED",
	1: "WAITING_APPROVAL",
	2: "REJECTED",
}
var Status_value = map[string]int32{
	"REGISTERED":       0,
	"WAITING_APPROVAL": 1,
	"REJECTED":         2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RegisterRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusReply struct {
	Status Status `protobuf:"varint,1,opt,name=status,enum=pairing.Status" json:"status,omitempty"`
}

func (m *StatusReply) Reset()                    { *m = StatusReply{} }
func (m *StatusReply) String() string            { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()               {}
func (*StatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "pairing.RegisterRequest")
	proto.RegisterType((*StatusReply)(nil), "pairing.StatusReply")
	proto.RegisterEnum("pairing.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Pairing service

type PairingClient interface {
	// Register a new client certificate
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type pairingClient struct {
	cc *grpc.ClientConn
}

func NewPairingClient(cc *grpc.ClientConn) PairingClient {
	return &pairingClient{cc}
}

func (c *pairingClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/pairing.Pairing/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pairing service

type PairingServer interface {
	// Register a new client certificate
	Register(context.Context, *RegisterRequest) (*StatusReply, error)
}

func RegisterPairingServer(s *grpc.Server, srv PairingServer) {
	s.RegisterService(&_Pairing_serviceDesc, srv)
}

func _Pairing_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pairing.Pairing/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pairing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pairing.Pairing",
	HandlerType: (*PairingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Pairing_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("pairing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xcc, 0x2c,
	0xca, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x1c, 0xb9,
	0xf8, 0x83, 0x52, 0xd3, 0x33, 0x8b, 0x4b, 0x52, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x21, 0x29, 0x2e, 0x8e, 0x9c, 0xfc, 0xe4, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x26, 0xb0,
	0x38, 0x9c, 0xaf, 0x64, 0xc6, 0xc5, 0x1d, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x1c, 0x94, 0x5a, 0x90,
	0x53, 0x29, 0xa4, 0xce, 0xc5, 0x56, 0x0c, 0xe6, 0x82, 0x0d, 0xe0, 0x33, 0xe2, 0xd7, 0x83, 0x59,
	0x0d, 0x55, 0x05, 0x95, 0xd6, 0xb2, 0xe1, 0x62, 0x83, 0x88, 0x08, 0xf1, 0x71, 0x71, 0x05, 0xb9,
	0xba, 0x7b, 0x06, 0x87, 0xb8, 0x06, 0xb9, 0xba, 0x08, 0x30, 0x08, 0x89, 0x70, 0x09, 0x84, 0x3b,
	0x7a, 0x86, 0x78, 0xfa, 0xb9, 0xc7, 0x3b, 0x06, 0x04, 0x04, 0xf9, 0x87, 0x39, 0xfa, 0x08, 0x30,
	0x0a, 0xf1, 0x70, 0x71, 0x04, 0xb9, 0x7a, 0xb9, 0x3a, 0x87, 0x00, 0xd5, 0x30, 0x19, 0xb9, 0x73,
	0xb1, 0x07, 0x40, 0xcc, 0x15, 0xb2, 0x01, 0x4a, 0x40, 0xfd, 0x20, 0x24, 0x01, 0xb7, 0x0d, 0xcd,
	0x5b, 0x52, 0x22, 0xe8, 0xee, 0x00, 0xb9, 0x56, 0x89, 0xc1, 0x49, 0x93, 0x4b, 0x2a, 0x39, 0x3f,
	0x57, 0x2f, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x2d, 0x27, 0xb5, 0xa2, 0x38, 0x37, 0x19,
	0xa6, 0xd6, 0x89, 0x33, 0x20, 0x09, 0x6a, 0x4d, 0x00, 0x63, 0x12, 0x1b, 0x38, 0xf0, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0xd6, 0xc7, 0x7d, 0x4d, 0x01, 0x00, 0x00,
}
